### ISSUE TITLE
代码与论文中的筛选方法不一致

### ISSUE THREAD

**Issue by Dian20011001** [HaochenLiu2000/KELP#1]
在代码中没有对所有实体路径集根据共享路径进行分割，代码中直接将所有的路径进行了与问题的嵌入向量的余弦相似度计算，取了topk1个就筛选结束了，其他部分筛选代码缺失

**Comment by HaochenLiu2000** [comment]
Thanks for commenting. Our code uses the same path method as in the paper, but in the paper we make it more suitable for writing. In addition, for MetaQA-1hop, we only used one k because it emphasizes the information of 1hop, and k2 is used in other datasets. Please point out the details if you have other concerns.
